### ISSUE TITLE
Inspecting source code cannot work in REPL (interactive python session) and is unexplained

### ISSUE THREAD

**Issue by joseortiz3** [deepgraph/deepgraph#11]
The code as-is names things (variables, columns, etc) by reading source code directly. This does not work when there is no source code, for instance when in an interactive session. Since much of data-science occurs in interactive sessions, this is (imo) a major limitation.

It is also extremely surprising and unexpected; the tutorial should mention that the package reads source code (for instance in the ball example).

**Comment by dominiktraxl** [comment]
It works for me, also in interactive sessions. Can you please provide a minimal example to reproduce the error?

**Comment by joseortiz3** [comment]
@dominiktraxl 

My minimal repro is to copy and paste the tutorial into VS Code interactive session (cross-platform) or Visual Studio interactive session (windows only). Some environments have interactive sessions that actually store source code, but its not standard.

```python
Python 3.7.3 (v3.7.3:ef4ec6ed12, Mar 25 2019, 22:22:05) [MSC v.1916 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> # for plots
... import matplotlib.pyplot as plt
>>>
>>> # the usual
... import numpy as np
>>> import pandas as pd
>>>
>>> import deepgraph as dg
>>> # notebook display
... %matplotlib inline
  File "<stdin>", line 2
    %matplotlib inline
    ^
SyntaxError: invalid syntax
>>> plt.rcParams['figure.figsize'] = 8, 6
>>> pd.options.display.max_rows = 10
>>> pd.set_option('expand_frame_repr', False)
>>> v = pd.read_csv('C:/Users/Joey/Downloads/flying_balls.csv', index_col=0)
>>> print(v)
      time            x          y  ball_id
0        0  1692.000000   0.000000        0
1        0  8681.000000   0.000000        1
2        0   490.000000   0.000000        2
3        0  7439.000000   0.000000        3
4        0  4998.000000   0.000000        4
...    ...          ...        ...      ...
1163    45  2812.552734  16.503178       39
1164    46  5686.915998  14.161693       10
1165    46  3161.729086  19.381823       14
1166    46  5594.233413  57.701712       37
1167    47  5572.216748  20.588750       37

[1168 rows x 4 columns]
>>> g = dg.DeepGraph(v)
>>> def x_dist(x_s,x_t):
...     dx = x_t - x_s
...     return dx
...
>>> g = create_edges(connectors=x_dist)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
NameError: name 'create_edges' is not defined
>>> g.create_edges(connectors=x_dist)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Users\Joey\Python37\lib\site-packages\deepgraph\deepgraph.py", line 607, in create_edges
    r_dtype_dic, transfer_features, no_transfer_rs, hdf_key)
  File "C:\Users\Joey\Python37\lib\site-packages\deepgraph\deepgraph.py", line 4741, in _initiate_create_edges
    Connector(connector)
  File "C:\Users\Joey\Python37\lib\site-packages\deepgraph\deepgraph.py", line 4555, in __init__
    super(Connector, self).__init__(fct)
  File "C:\Users\Joey\Python37\lib\site-packages\deepgraph\deepgraph.py", line 4490, in __init__
    source_code_return = inspect.getsourcelines(fct)[0][-1].strip()
  File "C:\Users\Joey\Python37\lib\inspect.py", line 955, in getsourcelines
    lines, lnum = findsource(object)
  File "C:\Users\Joey\Python37\lib\inspect.py", line 786, in findsource
    raise OSError('could not get source code')
OSError: could not get source code
```

What interactive environment are you using?

**Comment by dominiktraxl** [comment]
I'm using [IPython](https://ipython.org/) and [Jupyter Notebook](https://jupyter.org/), both are working with respect to `inspect.getsourcelines()`.

I'll leave this issue open, if anyone else is experiencing the above error, please say so. For now, I'm hesitant to look at this further, simply because of a lack of time and a Windows environment to test.

**Comment by joseortiz3** [comment]
@dominiktraxl Makes sense. FWIW, VS Code does not require a Windows environment, and is wildly popular across all platforms.
