### ISSUE TITLE
Can't install deepgraph

### ISSUE THREAD

**Issue by fredshu** [deepgraph/deepgraph#13]
I use Linux, tried to install with pip and "python setup.py install", both ways getting the following errors. I am not using Anaconda. Thanks for any help provided.

Requirement already satisfied: numpy>=1.6 in /home/fl/.local/lib/python3.6/site-packages (from deepgraph==0.2.1) (1.18.5)
Requirement already satisfied: pandas>=0.17.0 in /home/fl/.local/lib/python3.6/site-packages (from deepgraph==0.2.1) (1.1.4)
Requirement already satisfied: python-dateutil>=2.7.3 in /home/fl/.local/lib/python3.6/site-packages (from pandas>=0.17.0->deepgraph==0.2.1) (2.8.1)
Requirement already satisfied: pytz>=2017.2 in /home/fl/.local/lib/python3.6/site-packages (from pandas>=0.17.0->deepgraph==0.2.1) (2020.1)
Requirement already satisfied: six>=1.5 in /home/fl/.local/lib/python3.6/site-packages (from python-dateutil>=2.7.3->pandas>=0.17.0->deepgraph==0.2.1) (1.14.0)
Building wheels for collected packages: deepgraph

  Building wheel for deepgraph (setup.py) ... error
  ERROR: Command errored out with exit status 1:
   command: /usr/bin/python -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-2fb5bg_v/deepgraph_cc36448b921b4435ae46bb2115c18212/setup.py'"'"'; __file__='"'"'/tmp/pip-install-2fb5bg_v/deepgraph_cc36448b921b4435ae46bb2115c18212/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' bdist_wheel -d /tmp/pip-wheel-rvp9nk2y
       cwd: /tmp/pip-install-2fb5bg_v/deepgraph_cc36448b921b4435ae46bb2115c18212/
  Complete output (40 lines):
  running bdist_wheel
  running build
  running build_py
  creating build
  creating build/lib.linux-x86_64-3.6
  creating build/lib.linux-x86_64-3.6/deepgraph
  copying deepgraph/functions.py -> build/lib.linux-x86_64-3.6/deepgraph
  copying deepgraph/deepgraph.py -> build/lib.linux-x86_64-3.6/deepgraph
  copying deepgraph/__init__.py -> build/lib.linux-x86_64-3.6/deepgraph
  creating build/lib.linux-x86_64-3.6/tests
  copying deepgraph/../tests/test_DeepGraph.py -> build/lib.linux-x86_64-3.6/deepgraph/../tests
  Traceback (most recent call last):
    File "<string>", line 1, in <module>
    File "/tmp/pip-install-2fb5bg_v/deepgraph_cc36448b921b4435ae46bb2115c18212/setup.py", line 69, in <module>
      './*.cpp',
    File "/usr/local/lib/python3.6/dist-packages/setuptools/__init__.py", line 145, in setup
      return distutils.core.setup(**attrs)
    File "/usr/lib/python3.6/distutils/core.py", line 148, in setup
      dist.run_commands()
    File "/usr/lib/python3.6/distutils/dist.py", line 955, in run_commands
      self.run_command(cmd)
    File "/usr/lib/python3.6/distutils/dist.py", line 974, in run_command
      cmd_obj.run()
    File "/home/fl/.local/lib/python3.6/site-packages/wheel/bdist_wheel.py", line 192, in run
      self.run_command('build')
    File "/usr/lib/python3.6/distutils/cmd.py", line 313, in run_command
      self.distribution.run_command(command)
    File "/usr/lib/python3.6/distutils/dist.py", line 974, in run_command
      cmd_obj.run()
    File "/usr/lib/python3.6/distutils/command/build.py", line 135, in run
      self.run_command(cmd_name)
    File "/usr/lib/python3.6/distutils/cmd.py", line 313, in run_command
      self.distribution.run_command(command)
    File "/usr/lib/python3.6/distutils/dist.py", line 974, in run_command
      cmd_obj.run()
    File "/usr/local/lib/python3.6/dist-packages/setuptools/command/build_py.py", line 53, in run
      self.build_package_data()
    File "/usr/local/lib/python3.6/dist-packages/setuptools/command/build_py.py", line 126, in build_package_data
      srcfile in self.distribution.convert_2to3_doctests):
  TypeError: argument of type 'NoneType' is not iterable
  ----------------------------------------
  ERROR: Failed building wheel for deepgraph
  Running setup.py clean for deepgraph
Failed to build deepgraph
Installing collected packages: deepgraph
    Running setup.py install for deepgraph ... error
    ERROR: Command errored out with exit status 1:
     command: /usr/bin/python -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-2fb5bg_v/deepgraph_cc36448b921b4435ae46bb2115c18212/setup.py'"'"'; __file__='"'"'/tmp/pip-install-2fb5bg_v/deepgraph_cc36448b921b4435ae46bb2115c18212/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /tmp/pip-record-ped4jg0r/install-record.txt --single-version-externally-managed --user --prefix= --compile --install-headers /home/fl/.local/include/python3.6m/deepgraph
         cwd: /tmp/pip-install-2fb5bg_v/deepgraph_cc36448b921b4435ae46bb2115c18212/
    Complete output (42 lines):
    running install
    running build
    running build_py
    creating build
    creating build/lib.linux-x86_64-3.6
    creating build/lib.linux-x86_64-3.6/deepgraph
    copying deepgraph/functions.py -> build/lib.linux-x86_64-3.6/deepgraph
    copying deepgraph/deepgraph.py -> build/lib.linux-x86_64-3.6/deepgraph
    copying deepgraph/__init__.py -> build/lib.linux-x86_64-3.6/deepgraph
    creating build/lib.linux-x86_64-3.6/tests
    copying deepgraph/../tests/test_DeepGraph.py -> build/lib.linux-x86_64-3.6/deepgraph/../tests
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-install-2fb5bg_v/deepgraph_cc36448b921b4435ae46bb2115c18212/setup.py", line 69, in <module>
        './*.cpp',
      File "/usr/local/lib/python3.6/dist-packages/setuptools/__init__.py", line 145, in setup
        return distutils.core.setup(**attrs)
      File "/usr/lib/python3.6/distutils/core.py", line 148, in setup
        dist.run_commands()
      File "/usr/lib/python3.6/distutils/dist.py", line 955, in run_commands
        self.run_command(cmd)
      File "/usr/lib/python3.6/distutils/dist.py", line 974, in run_command
        cmd_obj.run()
      File "/usr/local/lib/python3.6/dist-packages/setuptools/command/install.py", line 61, in run
        return orig.install.run(self)
      File "/usr/lib/python3.6/distutils/command/install.py", line 589, in run
        self.run_command('build')
      File "/usr/lib/python3.6/distutils/cmd.py", line 313, in run_command
        self.distribution.run_command(command)
      File "/usr/lib/python3.6/distutils/dist.py", line 974, in run_command
        cmd_obj.run()
      File "/usr/lib/python3.6/distutils/command/build.py", line 135, in run
        self.run_command(cmd_name)
      File "/usr/lib/python3.6/distutils/cmd.py", line 313, in run_command
        self.distribution.run_command(command)
      File "/usr/lib/python3.6/distutils/dist.py", line 974, in run_command
        cmd_obj.run()
      File "/usr/local/lib/python3.6/dist-packages/setuptools/command/build_py.py", line 53, in run
        self.build_package_data()
      File "/usr/local/lib/python3.6/dist-packages/setuptools/command/build_py.py", line 126, in build_package_data
        srcfile in self.distribution.convert_2to3_doctests):
    TypeError: argument of type 'NoneType' is not iterable
    ----------------------------------------
ERROR: Command errored out with exit status 1: /usr/bin/python -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-2fb5bg_v/deepgraph_cc36448b921b4435ae46bb2115c18212/setup.py'"'"'; __file__='"'"'/tmp/pip-install-2fb5bg_v/deepgraph_cc36448b921b4435ae46bb2115c18212/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /tmp/pip-record-ped4jg0r/install-record.txt --single-version-externally-managed --user --prefix= --compile --install-headers /home/fl/.local/include/python3.6m/deepgraph Check the logs for full command output.

**Comment by dominiktraxl** [comment]
Did you solve the problem? Can you update your pip and setuptools, and try again?

**Comment by fredshu** [comment]
As per your suggestion, after updating pip and some tweaks in my environment, it seems to work. Many thanks!
